package br.com.syslib.enuns;

public enum TipoLogradouro {
	
	A(1,"Área"),
	AC(2,"Acesso"),
	ACA(3,"Acampamento"),
	ACL(4,"Acesso Local"),
	AD(5,"Adro"),
	AE(6,"Área Especial"),
	AER(7,"Aeroporto"),
	AL(8,"Alameda"),
	AMD(9,"Avenida Marginal Direita"),
	AME(10,"Avenida Marginal Esquerda"),
	AN(11,"Anel Viário"),
	ANT(12,"Antiga Estrada"),
	ART(13,"Artéria"),
	AT(14,"Alto"),
	ATL(15,"Atalho"),
	A_V(16,"Área Verde"),
	AV(17,"Avenida"),
	AVC(18,"Avenida Contorno"),
	AVM(19,"Avenida Marginal"),
	AVV(20,"Avenida Velha"),
	BAL(21,"Balneário"),
	BC(22,"Beco"),
	BCO(23,"Buraco"),
	BEL(24,"Belvedere"),
	BL(25,"Bloco"),
	BLO(26,"Balão"),
	BLS(27,"Blocos"),
	BLV(28,"Bulevar"),
	BSQ(29,"Bosque"),
	BVD(30,"Boulevard"),
	BX(31,"Baixa"),
	C(32,"Cais"),
	CAL(33,"Calçada"),
	CAM(34,"Caminho"),
	CAN(35,"Canal"),
	CH(36,"Chácara"),
	CHA(37,"Chapadão"),
	CIC(38,"Ciclovia"),
	CIR(39,"Circular"),
	CJ(40,"Conjunto"),
	CJM(41,"Conjunto Mutirão"),
	CMP(42,"Complexo Viário"),
	COL(43,"Colônia"),
	COM(44,"Comunidade"),
	CON(45,"Condomínio"),
	COR(46,"Corredor"),
	CPO(47,"Campo"),
	CRG(48,"Córrego"),
	CTN(49,"Contorno"),
	DSC(50,"Descida"),
	DSV(51,"Desvio"),
	DT(52,"Distrito"),
	EB(53,"Entre Bloco"),
	EIM(54,"Estrada Intermunicipal"),
	ENS(55,"Enseada"),
	ENT(56,"Entrada Particular"),
	EQ(57,"Entre Quadra"),
	ESC(58,"Escada"),
	ESD(59,"Escadaria"),
	ESE(60,"Estrada Estadual"),
	ESI(61,"Estrada Vicinal"),
	ESL(62,"Estrada de Ligação"),
	ESM(63,"Estrada Municipal"),
	ESP(64,"Esplanada"),
	ESS(65,"Estrada de Servidão"),
	EST(66,"Estrada"),
	ESV(67,"Estrada Velha"),
	ETA(68,"Estrada Antiga"),
	ETC(69,"Estação"),
	ETD(70,"Estádio"),
	ETN(71,"Estância"),
	ETP(72,"Estrada Particular"),
	ETT(73,"Estacionamento"),
	EVA(74,"Evangélica"),
	EVD(75,"Elevada"),
	EX(76,"Eixo Industrial"),
	FAV(77,"Favela"),
	FAZ(78,"Fazenda"),
	FER(79,"Ferrovia"),
	FNT(80,"Fonte"),
	FRA(81,"Feira"),
	FTE(82,"Forte"),
	GAL(83,"Galeria"),
	GJA(84,"Granja"),
	HAB(85,"Núcleo Habitacional"),
	IA(86,"Ilha"),
	IND(87,"Indeterminado"),
	IOA(88,"Ilhota"),
	JD(89,"Jardim"),
	JDE(90,"Jardinete"),
	LD(91,"Ladeira"),
	LGA(92,"Lagoa"),
	LGO(93,"Lago"),
	LOT(94,"Loteamento"),
	LRG(95,"Largo"),
	LT(96,"Lote"),
	MER(97,"Mercado"),
	MNA(98,"Marina"),
	MOD(99,"Modulo"),
	MRG(100,"Projeção"),
	MRO(101,"Morro"),
	MTE(102,"Monte"),
	NUC(103,"Núcleo"),
	NUR(104,"Núcleo Rural"),
	OUT(105,"Outeiro"),
	PAR(106,"Paralela"),
	PAS(107,"Passeio"),
	PAT(108,"Pátio"),
	PC(109,"Praça"),
	PCE(110,"Praça de Esportes"),
	PDA(111,"Parada"),
	PDO(112,"Paradouro"),
	PNT(113,"Ponta"),
	PR(114,"Praia"),
	PRL(115,"Prolongamento"),
	PRM(116,"Parque Municipal"),
	PRQ(117,"Parque"),
	PRR(118,"Parque Residencial"),
	PSA(119,"Passarela"),
	PSG(120,"Passagem"),
	PSP(121,"Passagem de Pedestre"),
	PSS(122,"Passagem Subterrânea"),
	PTE(123,"Ponte"),
	PTO(124,"Porto"),
	Q(125,"Quadra"),
	QTA(126,"Quinta"),
	QTS(127,"Quintas"),
	R(128,"Rua"),
	RI(129,"Rua Integração"),
	RL(130,"Rua de Ligação"),
	RP(131,"Rua Particular"),
	RV(132,"Rua Velha"),
	RAM(133,"Ramal"),
	RCR(134,"Recreio"),
	REC(135,"Recanto"),
	RER(136,"Retiro"),
	RES(137,"Residencial"),
	RET(138,"Reta"),
	RLA(139,"Ruela"),
	RMP(140,"Rampa"),
	ROA(141,"Rodo Anel"),
	ROD(142,"Rodovia"),
	ROT(143,"Rotula"),
	RPE(144,"Rua de Pedestre"),
	RPR(145,"Margem"),
	RTN(146,"Retorno"),
	RTT(147,"Rotatória"),
	SEG(148,"Segunda Avenida"),
	SIT(149,"Sitio"),
	SRV(150,"Servidão"),
	ST(151,"Setor"),
	SUB(152,"Subida"),
	TCH(153,"Trincheira"),
	TER(154,"Terminal"),
	TR(155,"Trecho"),
	TRV(156,"Trevo"),
	TUN(157,"Túnel"),
	TV(158,"Travessa"),
	TVP(159,"Travessa Particular"),
	TVV(160,"Travessa Velha"),
	UNI(161,"Unidade"),
	V(162,"Via"),
	VC(163,"Via Coletora"),
	VL(164,"Via Local"),
	VAC(165,"Via de Acesso"),
	VAL(166,"Vala"),
	VCO(167,"Via Costeira"),
	VD(168,"Viaduto"),
	V_E(169,"Via Expressa"),
	VER(170,"Vereda"),
	VEV(171,"Via Elevado"),
	VL_(172,"Vila"),
	VLA(173,"Viela"),
	VLE(174,"Vale"),
	VLT(175,"Via Litorânea"),
	VPE(176,"Via de Pedestre"),
	VRT(177,"Variante"),
	ZIG(178,"Zigue-Zague");
	
	private int codigo;
	private String descricao;
	
	private TipoLogradouro(int codigo, String descricao) {
		this.codigo = codigo;
		this.descricao = descricao;
		}

	public int getCodigo() {
		return codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	
}



